"""empty message

Revision ID: 8829a1b1b48b
Revises: 
Create Date: 2019-12-20 08:33:06.457110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8829a1b1b48b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('architect', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_architect'), 'projects', ['architect'], unique=False)
    op.create_index(op.f('ix_projects_date'), 'projects', ['date'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=60), nullable=True),
    sa.Column('subject', sa.String(length=80), nullable=True),
    sa.Column('keywords', sa.String(length=80), nullable=True),
    sa.Column('lesson', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_field'), 'lessons', ['field'], unique=False)
    op.create_index(op.f('ix_lessons_keywords'), 'lessons', ['keywords'], unique=False)
    op.create_index(op.f('ix_lessons_lesson'), 'lessons', ['lesson'], unique=False)
    op.create_index(op.f('ix_lessons_subject'), 'lessons', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_subject'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_lesson'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_keywords'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_field'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_architect'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
